// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/zelland.proto

package zelland

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenViewRequest_FileType int32

const (
	OpenViewRequest_UNKNOWN  OpenViewRequest_FileType = 0
	OpenViewRequest_IMAGE    OpenViewRequest_FileType = 1
	OpenViewRequest_MARKDOWN OpenViewRequest_FileType = 2
	OpenViewRequest_PDF      OpenViewRequest_FileType = 3
)

// Enum value maps for OpenViewRequest_FileType.
var (
	OpenViewRequest_FileType_name = map[int32]string{
		0: "UNKNOWN",
		1: "IMAGE",
		2: "MARKDOWN",
		3: "PDF",
	}
	OpenViewRequest_FileType_value = map[string]int32{
		"UNKNOWN":  0,
		"IMAGE":    1,
		"MARKDOWN": 2,
		"PDF":      3,
	}
)

func (x OpenViewRequest_FileType) Enum() *OpenViewRequest_FileType {
	p := new(OpenViewRequest_FileType)
	*p = x
	return p
}

func (x OpenViewRequest_FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpenViewRequest_FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_zelland_proto_enumTypes[0].Descriptor()
}

func (OpenViewRequest_FileType) Type() protoreflect.EnumType {
	return &file_proto_zelland_proto_enumTypes[0]
}

func (x OpenViewRequest_FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpenViewRequest_FileType.Descriptor instead.
func (OpenViewRequest_FileType) EnumDescriptor() ([]byte, []int) {
	return file_proto_zelland_proto_rawDescGZIP(), []int{2, 0}
}

type AnnotationAction_ActionType int32

const (
	AnnotationAction_CREATE AnnotationAction_ActionType = 0
	AnnotationAction_UPDATE AnnotationAction_ActionType = 1
	AnnotationAction_DELETE AnnotationAction_ActionType = 2
)

// Enum value maps for AnnotationAction_ActionType.
var (
	AnnotationAction_ActionType_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
	}
	AnnotationAction_ActionType_value = map[string]int32{
		"CREATE": 0,
		"UPDATE": 1,
		"DELETE": 2,
	}
)

func (x AnnotationAction_ActionType) Enum() *AnnotationAction_ActionType {
	p := new(AnnotationAction_ActionType)
	*p = x
	return p
}

func (x AnnotationAction_ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnnotationAction_ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_zelland_proto_enumTypes[1].Descriptor()
}

func (AnnotationAction_ActionType) Type() protoreflect.EnumType {
	return &file_proto_zelland_proto_enumTypes[1]
}

func (x AnnotationAction_ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnnotationAction_ActionType.Descriptor instead.
func (AnnotationAction_ActionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_zelland_proto_rawDescGZIP(), []int{3, 0}
}

// Wrapper for all WebSocket messages
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Ping
	//	*Envelope_OpenView
	//	*Envelope_Annotation
	//	*Envelope_Status
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_zelland_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zelland_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_zelland_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetPing() *KeepAlive {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Envelope) GetOpenView() *OpenViewRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_OpenView); ok {
			return x.OpenView
		}
	}
	return nil
}

func (x *Envelope) GetAnnotation() *AnnotationAction {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Annotation); ok {
			return x.Annotation
		}
	}
	return nil
}

func (x *Envelope) GetStatus() *ClientStatus {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Ping struct {
	Ping *KeepAlive `protobuf:"bytes,1,opt,name=ping,proto3,oneof"`
}

type Envelope_OpenView struct {
	OpenView *OpenViewRequest `protobuf:"bytes,2,opt,name=open_view,json=openView,proto3,oneof"`
}

type Envelope_Annotation struct {
	Annotation *AnnotationAction `protobuf:"bytes,3,opt,name=annotation,proto3,oneof"`
}

type Envelope_Status struct {
	Status *ClientStatus `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

func (*Envelope_Ping) isEnvelope_Payload() {}

func (*Envelope_OpenView) isEnvelope_Payload() {}

func (*Envelope_Annotation) isEnvelope_Payload() {}

func (*Envelope_Status) isEnvelope_Payload() {}

type KeepAlive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAlive) Reset() {
	*x = KeepAlive{}
	mi := &file_proto_zelland_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAlive) ProtoMessage() {}

func (x *KeepAlive) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zelland_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAlive.ProtoReflect.Descriptor instead.
func (*KeepAlive) Descriptor() ([]byte, []int) {
	return file_proto_zelland_proto_rawDescGZIP(), []int{1}
}

func (x *KeepAlive) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type OpenViewRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	AssetId       string                   `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Url           string                   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"` // https://host/assets/xyz
	FileType      OpenViewRequest_FileType `protobuf:"varint,3,opt,name=file_type,json=fileType,proto3,enum=zelland.OpenViewRequest_FileType" json:"file_type,omitempty"`
	Title         string                   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"` // For Markdown, initial state might be included here or fetched separately
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenViewRequest) Reset() {
	*x = OpenViewRequest{}
	mi := &file_proto_zelland_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenViewRequest) ProtoMessage() {}

func (x *OpenViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zelland_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenViewRequest.ProtoReflect.Descriptor instead.
func (*OpenViewRequest) Descriptor() ([]byte, []int) {
	return file_proto_zelland_proto_rawDescGZIP(), []int{2}
}

func (x *OpenViewRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *OpenViewRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *OpenViewRequest) GetFileType() OpenViewRequest_FileType {
	if x != nil {
		return x.FileType
	}
	return OpenViewRequest_UNKNOWN
}

func (x *OpenViewRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type AnnotationAction struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Type          AnnotationAction_ActionType `protobuf:"varint,1,opt,name=type,proto3,enum=zelland.AnnotationAction_ActionType" json:"type,omitempty"`
	FilePath      string                      `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"` // Or asset_id
	Data          *AnnotationData             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationAction) Reset() {
	*x = AnnotationAction{}
	mi := &file_proto_zelland_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationAction) ProtoMessage() {}

func (x *AnnotationAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zelland_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationAction.ProtoReflect.Descriptor instead.
func (*AnnotationAction) Descriptor() ([]byte, []int) {
	return file_proto_zelland_proto_rawDescGZIP(), []int{3}
}

func (x *AnnotationAction) GetType() AnnotationAction_ActionType {
	if x != nil {
		return x.Type
	}
	return AnnotationAction_CREATE
}

func (x *AnnotationAction) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *AnnotationAction) GetData() *AnnotationData {
	if x != nil {
		return x.Data
	}
	return nil
}

type AnnotationData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TargetText    string                 `protobuf:"bytes,2,opt,name=target_text,json=targetText,proto3" json:"target_text,omitempty"`
	ContextHash   string                 `protobuf:"bytes,3,opt,name=context_hash,json=contextHash,proto3" json:"context_hash,omitempty"` // SHA of surrounding paragraph for robust anchoring
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`                                  // The user's note
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationData) Reset() {
	*x = AnnotationData{}
	mi := &file_proto_zelland_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationData) ProtoMessage() {}

func (x *AnnotationData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zelland_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationData.ProtoReflect.Descriptor instead.
func (*AnnotationData) Descriptor() ([]byte, []int) {
	return file_proto_zelland_proto_rawDescGZIP(), []int{4}
}

func (x *AnnotationData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AnnotationData) GetTargetText() string {
	if x != nil {
		return x.TargetText
	}
	return ""
}

func (x *AnnotationData) GetContextHash() string {
	if x != nil {
		return x.ContextHash
	}
	return ""
}

func (x *AnnotationData) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *AnnotationData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ClientStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	DeviceName    string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientStatus) Reset() {
	*x = ClientStatus{}
	mi := &file_proto_zelland_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStatus) ProtoMessage() {}

func (x *ClientStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zelland_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStatus.ProtoReflect.Descriptor instead.
func (*ClientStatus) Descriptor() ([]byte, []int) {
	return file_proto_zelland_proto_rawDescGZIP(), []int{5}
}

func (x *ClientStatus) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ClientStatus) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

var File_proto_zelland_proto protoreflect.FileDescriptor

const file_proto_zelland_proto_rawDesc = "" +
	"\n" +
	"\x13proto/zelland.proto\x12\azelland\"\xe6\x01\n" +
	"\bEnvelope\x12(\n" +
	"\x04ping\x18\x01 \x01(\v2\x12.zelland.KeepAliveH\x00R\x04ping\x127\n" +
	"\topen_view\x18\x02 \x01(\v2\x18.zelland.OpenViewRequestH\x00R\bopenView\x12;\n" +
	"\n" +
	"annotation\x18\x03 \x01(\v2\x19.zelland.AnnotationActionH\x00R\n" +
	"annotation\x12/\n" +
	"\x06status\x18\x04 \x01(\v2\x15.zelland.ClientStatusH\x00R\x06statusB\t\n" +
	"\apayload\")\n" +
	"\tKeepAlive\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xcf\x01\n" +
	"\x0fOpenViewRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12>\n" +
	"\tfile_type\x18\x03 \x01(\x0e2!.zelland.OpenViewRequest.FileTypeR\bfileType\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"9\n" +
	"\bFileType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01\x12\f\n" +
	"\bMARKDOWN\x10\x02\x12\a\n" +
	"\x03PDF\x10\x03\"\xc8\x01\n" +
	"\x10AnnotationAction\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.zelland.AnnotationAction.ActionTypeR\x04type\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.zelland.AnnotationDataR\x04data\"0\n" +
	"\n" +
	"ActionType\x12\n" +
	"\n" +
	"\x06CREATE\x10\x00\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\"\x96\x01\n" +
	"\x0eAnnotationData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtarget_text\x18\x02 \x01(\tR\n" +
	"targetText\x12!\n" +
	"\fcontext_hash\x18\x03 \x01(\tR\vcontextHash\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"G\n" +
	"\fClientStatus\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceNameB)Z'github.com/zelland/daemon/proto/zellandb\x06proto3"

var (
	file_proto_zelland_proto_rawDescOnce sync.Once
	file_proto_zelland_proto_rawDescData []byte
)

func file_proto_zelland_proto_rawDescGZIP() []byte {
	file_proto_zelland_proto_rawDescOnce.Do(func() {
		file_proto_zelland_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_zelland_proto_rawDesc), len(file_proto_zelland_proto_rawDesc)))
	})
	return file_proto_zelland_proto_rawDescData
}

var file_proto_zelland_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_zelland_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_zelland_proto_goTypes = []any{
	(OpenViewRequest_FileType)(0),    // 0: zelland.OpenViewRequest.FileType
	(AnnotationAction_ActionType)(0), // 1: zelland.AnnotationAction.ActionType
	(*Envelope)(nil),                 // 2: zelland.Envelope
	(*KeepAlive)(nil),                // 3: zelland.KeepAlive
	(*OpenViewRequest)(nil),          // 4: zelland.OpenViewRequest
	(*AnnotationAction)(nil),         // 5: zelland.AnnotationAction
	(*AnnotationData)(nil),           // 6: zelland.AnnotationData
	(*ClientStatus)(nil),             // 7: zelland.ClientStatus
}
var file_proto_zelland_proto_depIdxs = []int32{
	3, // 0: zelland.Envelope.ping:type_name -> zelland.KeepAlive
	4, // 1: zelland.Envelope.open_view:type_name -> zelland.OpenViewRequest
	5, // 2: zelland.Envelope.annotation:type_name -> zelland.AnnotationAction
	7, // 3: zelland.Envelope.status:type_name -> zelland.ClientStatus
	0, // 4: zelland.OpenViewRequest.file_type:type_name -> zelland.OpenViewRequest.FileType
	1, // 5: zelland.AnnotationAction.type:type_name -> zelland.AnnotationAction.ActionType
	6, // 6: zelland.AnnotationAction.data:type_name -> zelland.AnnotationData
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_zelland_proto_init() }
func file_proto_zelland_proto_init() {
	if File_proto_zelland_proto != nil {
		return
	}
	file_proto_zelland_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Ping)(nil),
		(*Envelope_OpenView)(nil),
		(*Envelope_Annotation)(nil),
		(*Envelope_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_zelland_proto_rawDesc), len(file_proto_zelland_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_zelland_proto_goTypes,
		DependencyIndexes: file_proto_zelland_proto_depIdxs,
		EnumInfos:         file_proto_zelland_proto_enumTypes,
		MessageInfos:      file_proto_zelland_proto_msgTypes,
	}.Build()
	File_proto_zelland_proto = out.File
	file_proto_zelland_proto_goTypes = nil
	file_proto_zelland_proto_depIdxs = nil
}
